CREATE TABLE IF NOT EXISTS product_hero (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  eyebrow VARCHAR(255) NULL,
  title TEXT NOT NULL,
  description TEXT NULL,
  hero_image_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

