const { createAdminCrudController } = require('./crudControllerFactory');
const { recycledItemService } = require('../../services/recycledItemService');

const listFields = [
  { key: 'id', label: 'ID' },
  { key: 'name', label: '回收物名稱' },
  { key: 'code', label: '回收物代碼' },
  { key: 'category', label: '類型' },
  { key: 'status', label: '狀態' },
  { key: 'created_at', label: '建立時間' },
];

async function getFormFields(req, record) {
  const existing = await recycledItemService.listAll();
  const categories = Array.from(
    new Set(existing.map((x) => (x.category || '').trim()).filter(Boolean))
  ).sort((a, b) => a.localeCompare(b, 'zh-Hant'));

  const categoryOptions = [
    { value: '', label: '（不分類）' },
    ...categories.map((c) => ({ value: c, label: c })),
    { value: '__new__', label: '＋新增類型' },
  ];

  const fields = [
    { key: 'name', label: '回收物名稱', required: true },
    {
      key: 'category',
      label: '類型',
      type: 'select',
      options: categoryOptions,
      helpText: '可選擇既有類型；若要新增，請選「＋新增類型」。',
    },
    {
      key: 'new_category',
      label: '新增類型名稱',
      showWhenKey: 'category',
      showWhenValue: '__new__',
      required: true,
    },
    { key: 'description', label: '說明', type: 'textarea' },
    {
      key: 'status',
      label: '狀態',
      type: 'select',
      options: [
        { value: 'active', label: '啟用' },
        { value: 'inactive', label: '停用' },
      ],
    },
  ];

  // `code` is auto-generated by system on create.
  // For edit, show it as read-only.
  if (record && record.code) {
    fields.splice(1, 0, { key: 'code', label: '回收物代碼（系統產生）', readonly: true });
  }
  return fields;
}

async function preprocess(data) {
  const out = { ...data };
  // Prevent client from overwriting code in first version.
  delete out.code;
  if (out.category === '__new__') {
    out.category = out.new_category || null;
  }
  delete out.new_category;
  return out;
}

module.exports = createAdminCrudController({
  resourceSlug: 'recycled-items',
  title: '回收物類型',
  service: recycledItemService,
  listFields,
  formFields: getFormFields,
  preprocess,
});

